#!/bin/sh

interface_linklocal() {
        local macaddr="$(ubus call network.device status '{"name": "'"$1"'"}' | jsonfilter -e '@.macaddr')"
        local oldIFS="$IFS"; IFS=':'; set -- $macaddr; IFS="$oldIFS"

        echo "fe80::$(xor2 "$1")$2:$3ff:fe$4:$5$6"
}

#Wurde bereits ein privatekey generiert?
temp=$(uci get wireguard.wireguard.privatekey);
#Falls nicht, wird das hier nachgeholt
if [ "$?" -ne "0" ]; then
        uci set wireguard.wireguard.privatekey=$(wg genkey);
        uci commit wireguard
fi

#Ist wireguard überhaupt aktiviert??
if [ "$(uci get wireguard.wireguard.enabled)" == "true" ] || [ "$(uci get wireguard.wireguard.enabled)" == "1" ]; then

        #Ab hier kommen die Tests, ob die Verbindung steht
        CONNECTED=1

        INTERFACE=$(uci get wireguard.wireguard.iface)

        # Wireguardinterface vorhanden???
        ip addr show dev $INTERFACE > /dev/null
        if [ $? != 0 ]; then
                CONNECTED=0
        fi

        # VXLAN Interface vorhanden??
        if [ $CONNECTED != 0 ]; then
                ip addr show dev vxlan-wan > /dev/null
                if [ $? != 0 ]; then
                        CONNECTED=0
                fi
        fi

        # Funktioniert das VXLAN Interface ueberhaupt? Also gehen Daten rueber?
        if [ $CONNECTED != 0 ]; then
                RXBYTES=$(ip -statistics link show dev vxlan-wan |  sed '4q;d' | awk '{print $1}')
                if [ $RXBYTES == 0 ]; then
                        CONNECTED=0
                fi
        fi

        # Und funktioniert das Wireguardinterface? Kann ich den Server erreichen?
        if [ $CONNECTED != 0 ]; then
                ping -c1 -w2  $(uci get wireguard.wireguard.mcastgroup)
                if [ $? != 0 ]; then
                        CONNECTED=0
                fi
        fi
	
        # Wenn die Tests fehlgeschlagen sind, neu connecten
        if [ $CONNECTED == 0 ]; then

		# Falls ein Fehler bei Wireguard war, Module entladen und neuladen
		rmmod wireguard
		sleep 1
		modprobe wireguard

        	#Wieviele Hosts gibts denn in der Config?                                                          
        	MAX=10                                                                                             
        	ANZAHL=0                                                                                           
        	AUSWAHL=0                                                                                          
       	 	until [ $ANZAHL -eq $MAX ]                                                                         
       	 	do                                                                                                 
                	ANZAHL=`expr $ANZAHL + 1`                                                                  
                	uci show wireguard.peer_$ANZAHL 2>/dev/null > /dev/null                                    
                	if [ $? != 0 ]; then                                                                       
                        	break                                                                              
                	fi                                                                                         
        	done                                                                                               
        	ANZAHL=`expr $ANZAHL - 1`                                                                          
                                                                                                           
        	#Und welchen nehmen wir jetzt??                                                                    
        	SPEED1=0                                                                                           
        	I=0                                                                                                
        	until [ $I -eq $ANZAHL ]                                                                           
        	do                                                                                                 
                	I=`expr $I + 1`                                                                            
                	#Von allen Servern die durschnittliche potenzielle Geschwindigkeit pro Wireguard-Verbindung
                	URL=$(uci get wireguard.peer_$I.endpoint | cut -d':' -f1)                        
			SPEED2=$(curl https://$URL/speed.php -k)                                           
                	if [ $SPEED2 -gt $SPEED1 ]              # Wenn aktueller Server hoehren Wert hat,
                        		then AUSWAHL=$I                 # Servernummer speichern                 
                        	SPEED1=$SPEED2                                                           
                	fi                                                                               
        	done                                                                                     
        	URL=$(uci get wireguard.peer_$AUSWAHL.endpoint | cut -d':' -f1)                          
                                                                                                 
		#Die alten peers loeschen
		wg set $INTERFACE peer  $(wg |  awk 'BEGIN {RS=""} /endpoint/ {print $2}') remove
                batctl if del vxlan-wan
                ip link delete dev vxlan-wan
                ip link delete dev $INTERFACE
                PUBLICKEY=$(uci get wireguard.wireguard.privatekey | wg pubkey)
                echo $(uci get wireguard.wireguard.privatekey) > /tmp/wgpriv

                # Public Key zum vorher ausgesuchten Server hochladen
                curl -s -k --data-urlencode "pubkey=$PUBLICKEY" https://$URL/wireguard.php
		ip link add dev $INTERFACE type wireguard
                wg set $INTERFACE private-key /tmp/wgpriv
                sleep 5

                wg set $INTERFACE peer $(uci get wireguard.peer_$AUSWAHL.publickey) persistent-keepalive 25 allowed-ips fe80::/10,$(uci get wireguard.wireguard.mcastgroup)/32 endpoint $(uci get wireguard.peer_$AUSWAHL.endpoint)
                ip link set up dev $INTERFACE
                ip address add "$(interface_linklocal "$INTERFACE")" dev $INTERFACE

                sleep 5
                ip link add vxlan-wan type vxlan id "$(lua -e 'print(tonumber(require("gluon.util").domain_seed_bytes("gluon-mesh-vxlan", 3), 16))')" group $(uci get wireguard.wireguard.mcastgroup) dstport 4789 dev $INTERFACE
                ip link set up dev vxlan-wan
                sleep 5
                batctl if add vxlan-wan
                ip6tables -A INPUT -i $INTERFACE -j ACCEPT
                ip6tables -A FORWARD -i $INTERFACE -j ACCEPT

        fi
fi
